name: Deploy Lambda Functions
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  REGION_DEFAULT: "us-east-1"
  PROJECT_NAME: "video-processor"
  LAMBDA_BUCKET: "lambda-artifacts-video-processor"
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          for lambda in lambda/*/; do
            cd $lambda
            pip install -r requirements.txt
            pip install pytest pytest-cov pytest-mock
            cd ../..
          done
      - name: Run tests
        run: |
          chmod +x run_tests.sh
          ./run_tests.sh

  build-and-deploy:
    name: Build and Deploy Lambdas
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.REGION_DEFAULT }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgl1 \
            libglib2.0-0 \
            libsm6 \
            libxext6 \
            libxrender-dev \
            libgstreamer1.0-0 \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good
      
      - name: Build and upload Lambda packages
        run: |
          # Function to create Lambda package
          create_lambda_package() {
            local lambda_name=$1
            local lambda_dir_name=$2
            local temp_dir=$(mktemp -d)
            local zip_file="${lambda_dir_name}.zip"
            
            echo "Creating package for ${lambda_name}..."
            
            # Install dependencies in temporary directory
            if [ -f "lambda/${lambda_dir_name}/requirements.txt" ]; then
              pip install -r "lambda/${lambda_dir_name}/requirements.txt" --target "${temp_dir}" || {
                echo "Failed to install dependencies for ${lambda_dir_name}"
                return 1
              }
            fi
            
            # Copy source code
            if [ -d "lambda/${lambda_dir_name}/src" ]; then
              cp -r "lambda/${lambda_dir_name}/src/"* "${temp_dir}/" || {
                echo "Failed to copy source code for ${lambda_dir_name}"
                return 1
              }
            else
              echo "Warning: No src directory found for ${lambda_dir_name}"
              return 1
            fi
            
            # Create ZIP
            (cd "${temp_dir}" && zip -r9 "${GITHUB_WORKSPACE}/${zip_file}" .) || {
              echo "Failed to create ZIP for ${lambda_dir_name}"
              return 1
            }
            
            # Upload to S3
            aws s3 cp "${zip_file}" "s3://${LAMBDA_BUCKET}/${lambda_dir_name}/${zip_file}" || {
              echo "Failed to upload ${lambda_dir_name} to S3"
              return 1
            }
            
            # Update Lambda function
            aws lambda update-function-code \
              --function-name "${PROJECT_NAME}-${lambda_name}" \
              --s3-bucket "${LAMBDA_BUCKET}" \
              --s3-key "${lambda_dir_name}/${zip_file}" || {
              echo "Failed to update Lambda function ${lambda_name}"
              return 1
            }
            
            echo "Successfully processed ${lambda_name}"
          }
          
          create_lambda_package "video-processor" "video_processor" || {
            echo "Failed to process video-processor"
            exit 1
          }
          
          create_lambda_package "upload-handler" "upload_handler" || {
            echo "Failed to process upload-handler"
            exit 1
          }
          
          create_lambda_package "notification-handler" "notification_handler" || {
            echo "Failed to process notification-handler"
            exit 1
          }
      
      - name: Verify deployments
        run: |
          FUNCTIONS=("video-processor" "upload-handler" "notification-handler")
          for lambda in "${FUNCTIONS[@]}"; do
            echo "Verifying ${lambda}..."
            aws lambda get-function --function-name "${PROJECT_NAME}-${lambda}" || {
              echo "Failed to verify ${lambda}"
              exit 1
            }
          done